name: Build g_windows_print Plugin (Windows)

on:
  push:
    branches:
#      - dev
  workflow_dispatch:

jobs:
  build-plugin:
    name: Build g_windows_print Plugin
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ================= Flutter SDK =================
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: C:\hostedtoolcache\windows\flutter
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: stable

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      # ================= Dependencies =================
      - name: Install Dependencies
        run: flutter pub get

      # ================= Plugin Build =================
      - name: Cache g_windows_print plugin build
        uses: actions/cache@v3
        with:
          path: windows\build
          key: g_windows_print-build-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            g_windows_print-build-${{ runner.os }}-

      - name: Build g_windows_print plugin (Release)
        run: |
          cd windows
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      # ================= Upload Build Artifacts =================
      - name: Upload Plugin DLL and LIB
        uses: actions/upload-artifact@v4
        with:
          name: g_windows_print-plugin-build
          path: windows/build/Release/
